# LOCAL URL
@url = http://localhost:3000

# PRODUCTION URL
# @url = https://stable-bridge-backend.herokuapp.com/

###
GET {{url}}

###
GET {{url}}
Content-Type: application/json

{
  "forceError": true
}

###
POST {{url}}/pix

Content-Type: application/json

{
    "token": "SBRL",
    "networkId": 5,
    "amount": 1000
}